#!/usr/bin/env bash

###############################################################################
#                                                                             #
# AnsiWeather 1.00 (c) by Frederic Cambus 2013                                #
# Modified by Antoine Amarilli                                                #
# https://github.com/fcambus/ansiweather                                      #
#                                                                             #
# Created: 2013/08/29                                                         #
# Last Updated: 2013/10/21                                                    #
#                                                                             #
# AnsiWeather is released under the BSD 3-Clause license.                     #
# See LICENSE file for details.                                               #
#                                                                             #
###############################################################################



###[ Configuration options ]###################################################

config_file=~/.ansiweatherrc

function get_config {
	ret=""
	if [ -f $config_file ]
	then
		ret=$(grep $1 $config_file | awk -F\: '{print $2}')
	fi

	if [ "X$ret" = "X" ]
	then
		return 1
	else
		echo $ret
	fi
}

# Location : example "Moscow,RU"
location=$(get_config "location" || echo "Paris,FR")

# System of Units : "metric" or "imperial"
units=$(get_config "units" || echo "metric")

# Display symbols : "true" or "false" (requires an Unicode capable display)
symbols=$(get_config "symbols" || echo true)

# Choose how many prediction points to show
npred=$(get_config "symbols" || echo 10)


#### [ Colors and characters ]#################################################

background=$(get_config "background" || echo "\033[44m")
text=$(get_config "text" || echo "\033[36;1m")
data=$(get_config "data" || echo "\033[33;1m")
delimiter=$(get_config "delimiter" || echo "\033[35m=>")
dashes=$(get_config "dashes" || echo "\033[34m-")



###[ Unicode Symbols for icons ]###############################################

sun=$(get_config "sun" || echo "\033[33;1m\xe2\x98\x80")
moon=$(get_config "moon" || echo "\033[36m\xe2\x98\xbd")
clouds=$(get_config "clouds" || echo "\033[37;1m\xe2\x98\x81")
rain=$(get_config "rain" || echo "\xe2\x98\x94")



###[ Fetch Weather data ]######################################################

fetch_cmd=$(get_config "fetch_cmd" || echo "curl -s")

weather=$($fetch_cmd http://api.openweathermap.org/data/2.5/weather?q=$location\&units=$units)
forecast=$($fetch_cmd http://api.openweathermap.org/data/2.5/forecast?q=$location\&units=$units)



###[ Process Weather data ]####################################################

city=$(echo $weather | jq -r '.name')
temperature=$(echo $weather | jq '.main.temp')
humidity=$(echo $weather | jq '.main.humidity')
pressure=$(echo $weather | jq '.main.pressure')
sky=$(echo $weather | jq -r '.weather[0].main')
sunrise=$(echo $weather | jq '.sys.sunrise')
sunset=$(echo $weather | jq '.sys.sunset')




###[ Set the period ]##########################################################

now=$(date +%s)

if [ $now -ge $sunset ] || [ $now -le $sunrise ]
then
	period="night"
else
	period="day"
fi



###[ Set the scale ]###########################################################

case $units in
	metric)
		scale="°C"
		;;
	imperial)
		scale="°F"
		;;
esac



###[ Set icons ]###############################################################

if [ $symbols = true ]
then
	case $sky in
		Clear)
			if [ $period = "night" ]
			then
				icon="$moon "
			else
				icon="$sun  "
			fi
			;;
		Clouds)
			icon="$clouds  "
			;;
		Rain)
			icon="$rain  "
			;;
	esac
fi



###[ Display current Weather ]#################################################

echo -e "$background$text $city $delimiter$data $temperature $scale $icon$dashes$text Humidity $delimiter$data $humidity % $dashes$text Pressure $delimiter$data $pressure hPa \033[0m"


grey=`echo -e '\033[30m'`
blue=`echo -e '\033[36m'`
magenta=`echo -e '\033[35m'`
red=`echo -e '\033[31m'`
norm=`echo -e '\033[0;1m'`

paste <(echo $forecast | jq '.list | .[] | .dt_txt' |tr -d '"' |
    cut -d'-' -f3 | sed 's/^/'$norm'/;s/:00:00/h/;')\
  <(echo $forecast | jq -r '.list | .[] | .rain | .["3h"]' |
    sed 's/null//;s/^..*$/rain:&/;s/.*/'$red'&'$norm'/') \
  <(echo $forecast | jq -r '.list | .[] | .clouds.all' | sed 's/null/./' |
    sed 's/.*/'$grey'clds:&'$norm'/') \
  <(echo $forecast | jq -r '.list | .[] | .wind.speed' | sed 's/null/./' |
    sed 's/..\..*/'$red'&'$norm'/;s/.*/wind:&/') \
  <(echo $forecast | jq -r '.list | .[] | .main.pressure' |
    sed 's/\..*//;s/.*/'$grey'pres:&'$norm'/') \
  <(echo $forecast | jq -r '.list | .[] | .main.humidity' |
    sed 's/.*/'$grey'humd:&'$norm'/') \
  <(echo $forecast | jq -r '.list | .[] | .main.temp' |
    sed 's/\..*//;s/.*/temp:&/;s/^temp:[345].\..*/'$magenta'&'$norm'/;
    s/^temp:.\..*/'$blue'&'$norm'/;s/^temp:-.\..*/'$blue'&'$norm'/;') \
  <(echo $forecast | jq -r '.list | .[] | .weather[0].description') |
    head -$npred | column -t -s'	' |
    sed 's/ /'$grey'::'$norm'/;'

